nodeLinker: pnp

packageExtensions:
  "@astrojs/react@*":
    dependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
  "@lerna/legacy-package-management@*":
    peerDependencies:
      nx: "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
      react: "*"
      react-dom: "*"
      vite: "*"
  "@zag-js/date-utils@*":
    dependencies:
      "@internationalized/date": "*"
  ts-evaluator@*:
    dependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
